### ISSUE TITLE
Hope to support country code

### ISSUE THREAD

**Issue by lijy91** [erf/yaml_localizations#1]
Hope to support country code.

```dart
Locale('en', 'US')
```

or

```
Locale('zh', 'CN')
```

**Comment by erf** [comment]
Can you explain a bit more what you'd like to see?

Do you want to map both language and country code to a specific translation file?

E.g. something like:

```
Locale('en') -> lang/en.yaml
Locale('en', 'US') -> lang/en-US.yaml
```

**Comment by lijy91** [comment]
exactly what i wanted

**Comment by erf** [comment]
cool, I will fix that

**Comment by erf** [comment]
@lijy91 hey, can you test using the latest commit on the master branch if it looks ok?

**Comment by lijy91** [comment]
Already solved my needs

**Comment by erf** [comment]
I pushed a new version `yaml_localizations: ^0.3.0`to pub.dev
